### ISSUE TITLE
Script Failed error

### ISSUE THREAD

**Issue by coolcash** [Bitcrusher/Digitally-Imported-XBMC-plugin#16]
Running latest version
 Kodi 14.2 (Helix)

17:34:20 T:1488974912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/Digitally-Imported-XBMC-plugin-master/default.py", line 459, in <module>
                                                MusicAddonInstance.run()
                                              File "/storage/.kodi/addons/Digitally-Imported-XBMC-plugin-master/default.py", line 165, in run
                                                channelMeta = self.getChannelMetadata(html)
                                              File "/storage/.kodi/addons/Digitally-Imported-XBMC-plugin-master/default.py", line 273, in getChannelMetadata
                                                channelMeta = re_channelMeta.findall(html)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
17:34:21 T:1969275424   ERROR: GetDirectory - Error getting plugin://plugin.audio.di.fm/
17:34:21 T:1969275424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.di.fm/) failed
17:34:21 T:1488974912  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by Bitcrusher** [comment]
I've just pushed v3.0.9 that fixes this issue
